[project]
name = "zzros"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "pyqt5>=5.15.11",
    "pyserial>=3.5",
]
