# Enhanced YOLO OBB Model Configuration
# 增强的OBB模型 - 兼容当前Ultralytics版本
# 使用标准OBB模型 + 扩展训练数据 + 角度计算

# Parameters
nc: 1  # number of classes
scales: # model compound scaling constants
  # [depth, width, max_channels]
  n: [0.50, 0.25, 1024]  # YOLO11n summary
  s: [0.50, 0.50, 1024]  # YOLO11s summary
  m: [0.50, 0.75, 768]   # YOLO11m summary
  l: [1.00, 1.00, 512]   # YOLO11l summary
  x: [1.00, 1.50, 512]   # YOLO11x summary

# YOLO11n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 2, C3k2, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 2, C3k2, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLO11n head for OBB detection
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 2, C3k2, [512, False]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 2, C3k2, [256, False]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 2, C3k2, [512, False]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 2, C3k2, [1024, False]]  # 21 (P5/32-large)

  # Standard OBB Detection Head
  - [[15, 18, 21], 1, OBBDetect, [nc]]  # OBB detection head

# Training configuration
task: 'obb'  # OBB detection task

# Model information
info: |
  Enhanced YOLO OBB Model Configuration
  - 基于标准YOLO11n-obb架构
  - 兼容当前Ultralytics版本 (8.3.160)
  - 支持扩展训练数据格式: class + 8坐标 + 1角度
  - 训练时会忽略第10个角度值，只使用前9个值
  - 预测时从OBB角点计算实际角度
  - 角度系统: 0°=向上, 顺时针为正, 范围[-180°, 180°]
  
  训练策略:
  1. 使用扩展标签格式训练标准OBB模型
  2. 模型学习准确的OBB角点定位
  3. 后处理时从角点计算角度信息
  4. 实现角度感知的OBB检测 